/*
 * This file was generated by the Gradle 'init' task.
 */
pluginManagement {
    repositories {
        gradlePluginPortal()
    }
    includeBuild("plugins")
}
rootProject.name = "jasync-parent"
include(":jasync-runtime")
include(":jasync-reactive")
include(":jasync-test")
include(":jasync-spec")
include("jasync-asm")
include(":jasync-spring")
include(":jasync-agent")
include("jasync-core")
include("jasync-utils")
