/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
}

dependencies {
    api(project(":jasync-runtime"))
    api("io.github.vipcxj:easy-netty:0.0.12-SNAPSHOT")
}

description = "jasync-agent"
