/*
 * This file was generated by the Gradle 'init' task.
 */
val autoServiceVersion = rootProject.extra["auto_service_version"]

plugins {
    id("io.github.vipcxj.plugin.multiRelease")
}

multiRelease {
    defaultLanguageVersion(8)
    addLanguageVersion(9, 17)
}

dependencies {
    api(project(":jasync-spec"))
    api("io.github.vipcxj:schedule:1.0.2")
    api("org.jctools:jctools-core:3.3.0")
    compileOnly("com.github.spotbugs:spotbugs:4.2.0")
    testImplementation("org.junit.jupiter:junit-jupiter:5.10.0")
    api("com.google.auto.service:auto-service-annotations:$autoServiceVersion")
    annotationProcessor("com.google.auto.service:auto-service:$autoServiceVersion")
}

description = "JAsync Runtime"

java {
    withJavadocJar()
}

tasks.withType(JavaCompile::class.java) {
    doFirst {
        classpath.files.forEach {
            println("classpath for for $name are ${it}")
        }
        println("sourcepath for for $name are ${options.sourcepath}")
    }
}
