/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.github.vipcxj.plugin.multiRelease")
}

multiRelease {
    defaultLanguageVersion(8)
    addLanguageVersion(9, 17)
}

dependencies {
    api(project(":jasync-runtime"))
    testImplementation("org.junit.jupiter:junit-jupiter:5.7.2")
    compileOnly("org.projectlombok:lombok:1.18.22")
}

description = "JAsync Test"

java {
    withJavadocJar()
}
