/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
}

dependencies {
    api(project(":jasync-spec"))
    api(project(":jasync-reactive"))
    api("org.springframework.boot:spring-boot-autoconfigure:3.1.3")
    api("org.reactivestreams:reactive-streams:1.0.3")
    testImplementation(project(":jasync-runtime"))
    testImplementation("org.springframework.boot:spring-boot-starter-test:3.1.3")
    testImplementation("org.springframework.boot:spring-boot-starter-webflux:3.1.3")
    testImplementation("org.junit.jupiter:junit-jupiter:5.10.0")
}

description = "JAsync Spring"

java {
    withJavadocJar()
}
