/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
}

dependencies {
    api(project(":jasync-spec"))
    testImplementation("org.junit.jupiter:junit-jupiter:5.10.0")
    testImplementation("io.projectreactor:reactor-test:3.4.18")
    testImplementation(project(":jasync-runtime"))
    compileOnly("io.projectreactor:reactor-core:3.4.18")
}

description = "JAsync Reactive"

java {
    withJavadocJar()
}
