/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.github.vipcxj.plugin.multiRelease")
}

multiRelease {
    defaultLanguageVersion(8)
}

tasks.withType(JavaCompile::class.java) {
    options.compilerArgs.add("-XDenableSunApiLintControl")
}

description = "JAsync Utils"

java {
    withJavadocJar()
}
